[ERROR] 2019-07-09 12:58:18,175 | /opt/bench/erpnext/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2019-07-09 12:58:18.171830-127.0.0.1-e9a
[ERROR] 2019-07-10 12:34:28,563 | /opt/bench/erpnext/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2019-07-10 12:34:28.556765-127.0.0.1-e37
